### ISSUE TITLE
Error using geojson.py

### ISSUE THREAD

**Issue by mtravis** [edsu/twarc#103]
Hi there and thanks for the great tool.

I'm getting this error when trying to use the geojson.py function

```
Traceback (most recent call last):
  File "/opt/twarc/utils/geojson.py", line 127, in <module>
    if f['geometry']:
KeyError: 'geometry'
```

There are no directly geo-enabled tweets in my source but a few with the place bounding box supplied. 
http://all-mapped-out.co.uk/tweets.json

**Comment by hugovk** [comment]
Not sure if this is related, but Chrome reports an error for that JSON:

```
Error: Parse error on line 1:
...t_type": "recent"}}{"contributors": nul
----------------------^
Expecting 'EOF', '}', ',', ']'
```

And http://jsonlint.com/ gives:
```
Error: Parse error on line 95:
...ype": "recent"	}} {	"contributors": n
---------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

**Comment by edsu** [comment]
The json is line-oriented json, not a complete document. So that's not a problem.

**Comment by mtravis** [comment]
Thanks for the update. All working well now.
