### ISSUE TITLE
requests.exceptions.ContentDecodingError

### ISSUE THREAD

**Issue by lwrubel** [edsu/twarc#106]
I'm getting the following error with both 0.6.1 twarc installed via pip and with the latest master branch. This example below is from master. I'm using python 2.7.10.

```
(ENV)GLSS-C1MQL50:twarc lwrubel$ ./twarc.py --hydrate ids > full.json --profile=lwgwdev
Traceback (most recent call last):
  File "./twarc.py", line 469, in <module>
    main()
  File "./twarc.py", line 134, in main
    for tweet in tweets:
  File "./twarc.py", line 405, in hydrate
    resp = self.post(url, data={"id": ','.join(ids)})
  File "./twarc.py", line 214, in new_f
    resp = f(*args, **kwargs)
  File "./twarc.py", line 253, in new_f
    return f(self, *args, **kwargs)
  File "./twarc.py", line 267, in new_f
    return f(self, *args, **kwargs)
  File "./twarc.py", line 442, in post
    self.last_response = self.client.post(*args, **kwargs)
  File "/Users/lwrubel/projects/twarc/ENV/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/lwrubel/projects/twarc/ENV/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/lwrubel/projects/twarc/ENV/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/Users/lwrubel/projects/twarc/ENV/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/lwrubel/projects/twarc/ENV/lib/python2.7/site-packages/requests/models.py", line 669, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect data check',))
```
It happens intermittently. (I realized later I used the --profile flag incorrectly, with an "=", but I see that it still runs.)

**Comment by edsu** [comment]
Thanks @lwrubel ; I'm trying to hydrate 3M tweets with twarc v0.6.1 and python v2.7.10. I'll let you know how it goes? Would it run for a while before you got that error?

**Comment by edsu** [comment]
I'm just curious, if you install twarc with pip why are you running it with `./twarc.py` ?

**Comment by edsu** [comment]
I got one too!

```
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect data check',))
```

**Comment by lwrubel** [comment]
The example here is from running via the cloned repo, not pip. Sorry I didn't make that clearer. But I did get the error with the pip installed version too. 

(I cloned the repo to see if the other issue I mentioned, described in #98, was still happening. I might be misunderstanding, but it doesn't look like that bug fix is in the pypi version).

**Comment by edsu** [comment]
Wow, you're right! The timeout catching behavior is on master but not in v0.6.1 on PyPI. I don't know how that happened but it will get updated during the next release.

**Comment by lwrubel** [comment]
Thanks for confirming! I'll just use master until then.

**Comment by edsu** [comment]
If you want you can try the [gzip-errors](https://github.com/edsu/twarc/tree/gzip-errors) branch to see if that fix helps you. I'm testing it locally here at the moment.

**Comment by edsu** [comment]
twarc caught and recovered from 8 of these gzip decoding errors as I collected 1M tweets over the past 12 hours or so. I just released [v0.6.2](https://pypi.python.org/pypi/twarc/0.6.2) to PyPI which includes that timeout handling as well. 

Thanks for raising the issue!

**Comment by lwrubel** [comment]
Thanks for fixing that so quickly. I've been running --hydrate with the
gzip-errors branch this morning and it's been going for several hours with
no problems.

On Wed, Jun 1, 2016 at 10:11 AM, Ed Summers <notifications@github.com>
wrote:

> twarc caught and recovered from 8 of these gzip decoding errors as I
> collected 1M tweets over the past 12 hours or so. I just released v0.6.2
> <https://pypi.python.org/pypi/twarc/0.6.2> to PyPI which includes that
> timeout handling as well.
>
> Thanks for raising the issue!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edsu/twarc/issues/106#issuecomment-223004512>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABi1qZhfFgelytvqY0iSw-Zd6Z3iKoUTks5qHZMYgaJpZM4Iq35B>
> .
>



-- 


Laura Wrubel
Software Development Librarian
George Washington University Libraries
2130 H St NW
Washington, DC 20052
202-994-6536
lwrubel@gwu.edu

**Comment by edsu** [comment]
Sure thing. If you `grep WARN twarc.log` you should see if it caught any errors.

**Comment by lwrubel** [comment]
Caught 5 gzip decoding errors, no other errors happened.

On Wed, Jun 1, 2016 at 10:32 AM, Ed Summers <notifications@github.com>
wrote:

> Sure thing. If you grep WARN twarc.log you should see if it caught any
> errors.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edsu/twarc/issues/106#issuecomment-223011186>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABi1qSI6Ce-mDScOtWVTTFw3H1NteslEks5qHZftgaJpZM4Iq35B>
> .
>



-- 


Laura Wrubel
Software Development Librarian
George Washington University Libraries
2130 H St NW
Washington, DC 20052
202-994-6536
lwrubel@gwu.edu
