### ISSUE TITLE
secrets and keys

### ISSUE THREAD

**Issue by shawngraham** [edsu/twarc#47]
Hi Ed,

So I got consumer secret etc from https://dev.twitter.com/apps/new correctly set up. I assumed that I just put these into twarc.py at lines 33-36, but when I run it, I still get the error message from lines 39-41. So, not being overly familiar with python, can you talk me through putting these into my environment? Mac, PC, as I'd like to get my students exploring the possibilities and I have to be able to talk them through both.

Thanks!

**Comment by edsu** [comment]
I normally do this by putting them in a env.sh file like this:

    export CONSUMER_KEY="CONSUMERKEY"
    export CONSUMER_SECRET="CONSUMERSECRET"
    export ACCESS_TOKEN="ACCESS-TOKEN"
    export ACCESS_TOKEN_SECRET="ACCESSTOKENSECRET"

and then:

    source env.sh

to get them into the environment...

**Comment by shawngraham** [comment]
that totally worked. thank you! I would not have stumbled over that solution. this is *awesome*

**Comment by edsu** [comment]
Nice! Sometimes I think twarc.py should just take those as command line arguments. But it seems to be a familiar pattern that other tools use.
