### ISSUE TITLE
Syntax Error During Installation (Python3)

### ISSUE THREAD

**Issue by tristandahn** [edsu/twarc#50]
I'm wondering if you can help me. I'm encountering a syntax error while attempting to install. I'm running Python 3.4 on Mac OSX 10.7.5. 

Any help would be appreciated. Thanks!

Here is the log from the terminal:

vpn166047:~ tristandahn$ pip install twarc
Downloading/unpacking twarc
  Downloading twarc-0.1.2.tar.gz
  Running setup.py (path:/private/var/folders/v2/vv94gk4n6ns3s3ywf8bjvmw40000gn/T/pip_build_tristandahn/twarc/setup.py) egg_info for package twarc
    
Downloading/unpacking oauth2 (from twarc)
  Downloading oauth2-1.5.211.tar.gz
  Running setup.py (path:/private/var/folders/v2/vv94gk4n6ns3s3ywf8bjvmw40000gn/T/pip_build_tristandahn/oauth2/setup.py) egg_info for package oauth2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/v2/vv94gk4n6ns3s3ywf8bjvmw40000gn/T/pip_build_tristandahn/oauth2/setup.py", line 18
        print "unable to find version in %s" % (VERSIONFILE,)
                                           ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/v2/vv94gk4n6ns3s3ywf8bjvmw40000gn/T/pip_build_tristandahn/oauth2/setup.py", line 18

    print "unable to find version in %s" % (VERSIONFILE,)

                                       ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/var/folders/v2/vv94gk4n6ns3s3ywf8bjvmw40000gn/T/pip_build_tristandahn/oauth2
Storing debug log for failure in /Users/tristandahn/.pip/pip.log

**Comment by phette23** [comment]
I have the same problem on my Mac when I run `pip3 install twarc`. It looks like a problem in the OAuth2 dependency, see simplegeo/python-oauth2#147 where someone reports not being able to install on 3.3. It's a simple print statement fix but for now it kills python 3 installs.

**Comment by edsu** [comment]
Perhaps we should be using https://pypi.python.org/pypi/oauthlib ?
