### ISSUE TITLE
Incomplete results since recent releases

### ISSUE THREAD

**Issue by remagio** [edsu/twarc#53]
I have daily runs of lots of keywords & hashtags dump, but all runs querying for simple keywords results contains only last 8-12 days of twitter. I tested it too with Debian and OSX.
In my case happens with all searches.

In the past months I was able to get both: deltas and entire history. Since a few days, and before last release too, I was no more able to get entire deltas (if the batch didn't run since a while). Neither entire history.

Some of this daily are to check & compare history in verifying if releases or twitter is working fine.
There are no errors so at first I thought again in Twitter search API issues, anyone else ?

**Comment by edsu** [comment]
So possibly a resurgence of this problem from the Twitter API?

https://twittercommunity.com/t/0-status-after-a-next-result-request/22368

**Comment by remagio** [comment]
Yes, I checked that problems on search API only that couple of day. Since yesterday, Luckily, I was able again to monitor our President election in Twitter and I got too that day's tweets.
Probably there were some probs on Twitter releasing their new futures.
