### ISSUE TITLE
TypeError on archive.py

### ISSUE THREAD

**Issue by kayiwa** [edsu/twarc#60]
I am unable to get utils/archive.py to work anymore. I am able to replicate this on two machines and will continue to check to ensure this is pilot error. In the meantime. 

Run a twarc.py --search yoursearch > tweets.json

The utils/archive.py yoursearch /path/to/save

produces (in my case)

Traceback (most recent call last):
  File "twarc/utils/archive.py", line 110, in <module>
    main()
  File "twarc/utils/archive.py", line 62, in main
    t = twarc.Twarc()
TypeError: __init__() takes exactly 5 arguments (1 given)

Cheers,
./fxk

**Comment by edsu** [comment]
Ah yes, Twarc needs to be instantiated with the keys now, and archive.py hasn't been updated to do that yet. Thanks for the heads up!
