### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by edsu** [edsu/twarc#64]
It would be handy if twarc had a notion of profiles, similar to amazon's aws-cli. This way the various keys could be saved in a file, and there could be a default.

Wwhen started without any keys twarc could prompt for the consumer keys, give the user a URL to visit in their browser to get the access keys, and then save all the keys in their default profile ($HOME/.twarcrc).

**Comment by hugovk** [comment]
I'm not familiar with aws-cli, but for my Twitter bots I use a (YAML) config file containing the four keys and secrets and pass that file as an argument.

For example:
https://github.com/hugovk/wotdbot/blob/master/data/wotdbot_example.yaml
https://github.com/hugovk/wotdbot/blob/master/wotdbot.py#L15-22

Would something like that be useful? Shall I make a PR?

**Comment by edsu** [comment]
Yes, YAML would be great. A PR would be most welcome!

**Comment by edsu** [comment]
This got done, but never got closed!
