### ISSUE TITLE
Get All Followers of other Account and store in File

### ISSUE THREAD

**Issue by indokely** [edsu/twarc#66]
Hello Team,

Can I achieve this ?

I want All Followers of "Any Account" and store in File

Please help

**Comment by phette23** [comment]
You want to find all the followers of an account? This is not, as far as I know, something that twarc itself can do, but can be achieved with the Twitter API. I think the relevant API call information is here: https://dev.twitter.com/rest/reference/get/followers/ids

**Comment by edsu** [comment]
Yeah, twarc is really oriented around the tweets. If you are a pythonista definitely check out Tweepy which makes interacting with the Twitter API a snap.
