### ISSUE TITLE
Archive a single user's timeline?

### ISSUE THREAD

**Issue by hugovk** [edsu/twarc#70]
What would be the best way to archive a single user's tweets?

One way is to search for their @ username, and then filter by creator, but is there a cleaner way?

**Comment by edsu** [comment]
You can only get the last week via the search API (--search in twarc). If that's ok then you can use a query of 'from:username'. If you want to get more you can get up to 3,200 via Twitter's [statuses/user_timeline](https://dev.twitter.com/rest/reference/get/statuses/user_timeline) API call. But twarc doesn't let you do that. 

If you are wanting to use the streaming API to capture the tweets as they come in Twitter's [follow API call](https://dev.twitter.com/streaming/overview/request-parameters#follow) should work for that. But unfortunately twarc doesn't expose that API call yet. Let me know if that's what you are trying to do.

**Comment by hugovk** [comment]
Thanks, statuses/user_timeline looks like what I want, I'll check Tweepy.
