### ISSUE TITLE
streaming error

### ISSUE THREAD

**Issue by flinches** [edsu/twarc#74]
Hello,

I am using your script for school and I noticed when running it as library for streaming, it sometimes (one per minute) raise error (ERROR:root:json parse error: No JSON object could be decoded - ). Can I ask you what to do with that to make it work properly?

Thanks a lot.

Filip Hadac

**Comment by flinches** [comment]
Is it this?

Blank lines
On slow streams, some messages may be blank lines which serve as “keep-alive” signals to prevent clients and other network infrastructure from assuming the stream has stalled and closing the connection.

**Comment by edsu** [comment]
Yes, exactly. It would be useful for twarc not to log these that way right? They won't get written to the data output incidentally.

**Comment by edsu** [comment]
Also, I'm kind of curious to hear how you are using twarc in school, since I work in a university setting where we've been thinking about instructional uses of teaching twitter data collection.

**Comment by edsu** [comment]
I'm just pushed this up to PyPI too as v0.3.2 if you have installed twarc via pip. Let me know if you notice any problems!

**Comment by flinches** [comment]
Thanks. It seems to be ok now. And I use it in school for some research group. They gave me project to streaming data from Twitter for many keywords, saving them to files and then next working with it.

**Comment by edsu** [comment]
Excellent, that's just the use case it was created for. If you go looking for an app to manage data collection like this you might be interested in https://github.com/gwu-libraries/social-feed-manager which manages stuff for you, and pretty much lets the researchers decide what to collect.

**Comment by flinches** [comment]
Oh thanks. I will look at it and consider usage.

**Comment by flinches** [comment]
Hello, 

can I ask you one question? I have another problem, but i don't know if it is mine or yours. I am getting error 406: Not Acceptable. First time I got it after cca 66 hours and second time it was after cca 86 hours of streaming. I am still using Twarc as library and cannot find anything what could help me. Everything worked well but after that time there was error and then it was just repeating this error. Do you know where could be a problem?

Thanks a lot.

Filip Hadac

**Comment by edsu** [comment]
Interesting, did you can get any kind of stack trace?

**Comment by flinches** [comment]
I cannot get stack trace now, because I already quit application and run it again, because I am already using it to stream data what we need. Also it is not easy to debug it for me because it is running on server and error is often after 3 days. But i will implement some stack trace to script for next run and will see.

**Comment by edsu** [comment]
If you run it in a screen session you should be able to reconnect after a few days and see the stack trace. If you want I can update the [catch-404](https://github.com/edsu/twarc/tree/catch-404s) branch to also catch 406, and see if that helps you?

**Comment by flinches** [comment]
It is ok. I will try it once more and if it fails again, I will let you know and then you can update it. But thanks.
