### ISSUE TITLE
use six

### ISSUE THREAD

**Issue by edsu** [edsu/twarc#76]
Instead of trying to load different config modules for different versions twarc should use six.

**Comment by hugovk** [comment]
I probably wouldn't add another dependency if it's just to remove this:
```python
try:
    import configparser  # Python 3
except ImportError:
    import ConfigParser as configparser  # Python 2
```
See also https://docs.python.org/2/glossary.html#term-eafp

**Comment by edsu** [comment]
Fair enough :-)
