### ISSUE TITLE
Help with first run

### ISSUE THREAD

**Issue by shirish93** [edsu/twarc#87]
Hello,

Could you help me get started for my first run please? I created .twarc file in my home directory with the necessary details, and pip installed twarc. The getting started part of readme is not clear with what is to be done next .. Does one go to python installation directory and manually run the file from the command line, or is there some other step that needs to be done before?

After following those steps, this was the resulting stack trace:

`
 File "twarc.py", line 416, in <module>
    main()
  File "twarc.py", line 87, in main
    credentials = load_config(args.config, args.profile)
  File "twarc.py", line 145, in load_config
    config.read(filename)
  File "/usr/sup/Python-3.4.2/lib/python3.4/configparser.py", line 672, in read
    self._read(fp, filename)
  File "/usr/sup/Python-3.4.2/lib/python3.4/configparser.py", line 1058, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/h/spokha01/.twarc', line: 
consumer_key=MY_SECRET_KEY`
Thank you!
Shirish

**Comment by edsu** [comment]
So I guess you figured out? Is there anything twarc can do to help ease whatever pain you ran into?

**Comment by shirish93** [comment]
Hi !

Thanks for the response! It might be worth the time to do a couple of paras of 'get started' in documentation. An IPython notebook might have helped, though I am myself good to go : )

**Comment by edsu** [comment]
Ok that's a good idea, thanks!
