### ISSUE TITLE
python3 build is broken

### ISSUE THREAD

**Issue by edsu** [edsu/twarc#90]
It looks like the python3 build is broken because the last streaming test `test_locations` takes forever, and Travis gives up. Unfortunately this test has been failing for a while but a glitch in the setup.py was causing the failing test suite to go unnoticed by Travis.

What is actually going on is Twitter is giving back this error message:

```
420 Client Error: Enhance Your Calm
```

For the filter API call. I think what is happening is the previous two streaming requests are still open, and it is unable to open a third. The streaming requests are still open because a generator has opened them and is accumulating results to be iterated through. 

Is there a way to signal to the generator that we are done in the test? Or perhaps a method could be added to close the open streaming connections somehow?

The good news is there isn't an underlying problem with the `--locations` functionality. If you comment out one of the other streaming tests you can see that it passes just fine. It's interesting that the tests all pass on python2.7.

**Comment by hugovk** [comment]
I see it sometimes fails for Python 3.4, sometimes 3.4 and 3.5, sometimes both.

One option is to just skip them for Python 3, but then regressions can creep in, especially Python 3 bugs when new code is only developed for Python 2.

If the code under test can return an exception, the test can catch it and just return without failing any asserts.

If there's not a problem with the `--locations` functionality, is there a problem with the way tests are calling code under test? Or a problem somewhere else in the code under test?

It sounds like the best thing would be to be able to close a stream once it's been finished with. I can imagine someone may want to use three streams in a row, and once you're done with one you don't need it to generate more.
